#!/usr/bin/env ruby

require_relative 'lib/saturncicli/client'

begin
  client = SaturnCICLI::Client.new(
    username: ENV["SATURNCI_API_USERNAME"],
    password: ENV["SATURNCI_API_PASSWORD"]
  )

  client.execute(ARGV.join(" "))
rescue StandardError => e
  puts e.message
end
