#!/usr/bin/env ruby

require_relative 'lib/saturnci/client'

begin
  client = SaturnCI::Client.new(
    username: ENV["SATURNCI_API_USERNAME"],
    password: ENV["SATURNCI_API_PASSWORD"]
  )
rescue StandardError => e
  puts e.message
  exit
end
