apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${TAG}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${TAG}
  template:
    metadata:
      labels:
        app: ${TAG}
    spec:
      containers:
      - name: ${TAG}
        image: registry.digitalocean.com/saturnci/${TAG}
