default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>

development:
  <<: *default
  database: saturn_development

test:
  <<: *default
  database: saturn_test

production:
  <<: *default
  database: saturn_production
  username: saturn
  password:
