apiVersion: apps/v1
kind: Deployment
metadata:
  name: saturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saturn
  template:
    metadata:
      labels:
        app: saturn
    spec:
      containers:
      - name: saturn
        image: 588695668471.dkr.ecr.us-east-2.amazonaws.com/saturn:$TAG
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_PORT
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: RAILS_ENV
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: SATURNCI_USERNAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_USERNAME
        - name: SATURNCI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_PASSWORD
