apiVersion: apps/v1
kind: Deployment
metadata:
  name: saturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saturn
  template:
    metadata:
      labels:
        app: saturn
    spec:
      containers:
      - name: saturn
        image: registry.digitalocean.com/saturnci/saturnci:$TAG
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_PORT
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: RAILS_ENV
        - name: SATURNCI_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_API_USERNAME
        - name: SATURNCI_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_API_PASSWORD
        - name: SATURNCI_INSTALLATION_URL
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_INSTALLATION_URL
        - name: SATURNCI_HOST
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_HOST
        - name: GITHUB_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_OAUTH_CLIENT_ID
        - name: GITHUB_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_OAUTH_CLIENT_SECRET
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_APP_ID
        - name: GITHUB_PRIVATE_PEM
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_PRIVATE_PEM
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: DIGITALOCEAN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DIGITALOCEAN_ACCESS_TOKEN
      initContainers:
      - name: saturn-migrations
        image: registry.digitalocean.com/saturnci/saturnci:$TAG
        command: ['sh', '-c', 'rails db:migrate:concurrent']
        env:
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DATABASE_PORT
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: RAILS_ENV
        - name: SATURNCI_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_API_USERNAME
        - name: SATURNCI_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_API_PASSWORD
        - name: SATURNCI_INSTALLATION_URL
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_INSTALLATION_URL
        - name: SATURNCI_HOST
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: SATURNCI_HOST
        - name: GITHUB_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_OAUTH_CLIENT_ID
        - name: GITHUB_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_OAUTH_CLIENT_SECRET
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_APP_ID
        - name: GITHUB_PRIVATE_PEM
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: GITHUB_PRIVATE_PEM
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: DIGITALOCEAN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: saturn-secrets
              key: DIGITALOCEAN_ACCESS_TOKEN
