#!/bin/bash

# Example usage: ./deploy mednote production

APP_VERSION=$(date +%s)
ENVIRONMENT=$1
TAG="$ENVIRONMENT-$APP_VERSION"
echo "Deploying $TAG"
cd ..
docker build --platform linux/amd64 -t $TAG -f Dockerfile.production .
cd -
docker tag $TAG 588695668471.dkr.ecr.us-east-2.amazonaws.com/saturn:$TAG

./auth
docker push 588695668471.dkr.ecr.us-east-2.amazonaws.com/saturn:$TAG

./apply $ENVIRONMENT $TAG
