#!/bin/bash

# Example usage: ./deploy production

APP_VERSION=$(date +%s)
ENVIRONMENT=$1
TAG="$ENVIRONMENT-$APP_VERSION"
echo "Deploying $TAG"

cd ..
docker build --platform linux/amd64 -t $TAG -f Dockerfile.production .
cd -

doctl registry login
docker tag $TAG registry.digitalocean.com/saturnci/$TAG
docker push registry.digitalocean.com/saturnci/$TAG

./apply $ENVIRONMENT $TAG
