---
version: "3.8"

services:
  aws-cli:
    image: aws-cli
    volumes:
      - .:/usr/src:cached
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
      - ~/.kube:/root/.kube
      - ~/.config/helm:/root/.config/helm
      - ~/.cache/helm:/root/.cache/helm
    working_dir: /usr/src
