apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saturn-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: app.saturnci.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: saturn-service
            port:
              number: 80
