name: Rails CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: saturn
          POSTGRES_PASSWORD: saturn
          POSTGRES_DB: saturn_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_USERNAME: saturn
      DATABASE_PASSWORD: saturn
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.138.0
        with:
          bundler-cache: true
      - name: Install rails dependencies
        run: bundle install
      - name: Create DB
        run: bundle exec rails db:create
      - name: Run tests
        run: bundle exec rspec
