name: Rails CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file .saturnci/Dockerfile --tag my-rails-app

    - name: Run tests
      env:
        DATABASE_USERNAME: saturn
        DATABASE_PASSWORD: saturn
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        RAILS_ENV: test
      run: docker run -e DATABASE_USERNAME -e DATABASE_PASSWORD -e DATABASE_HOST -e DATABASE_PORT my-rails-app bundle exec rspec
