name: Rails CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          DATABASE_USERNAME: saturn
          DATABASE_PASSWORD: saturn
          DATABASE_PORT: 5432
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file .saturnci/Dockerfile --tag my-rails-app

    - name: Run tests
      env:
        DATABASE_USERNAME: saturn
        DATABASE_PASSWORD: saturn
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
        RAILS_ENV: test
      run: docker run -e DATABASE_USERNAME -e DATABASE_PASSWORD -e DATABASE_HOST -e DATABASE_PORT my-rails-app bundle exec rspec
