name: Rails CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_USERNAME: saturn
      DATABASE_HOST: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      RAILS_ENV: test
      REDIS_URL: redis://redis:6379/0

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file .saturnci/Dockerfile --tag my-rails-app

    - name: Run tests
      run: docker run -e DATABASE_USERNAME -e DATABASE_PASSWORD -e DATABASE_HOST -e DATABASE_PORT -e RAILS_ENV -e REDIS_URL my-rails-app bundle exec rspec
