name: Rails CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_USER: saturn
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready -U saturn
          --health-interval 10s
          --health-timeout 2s
          --health-retries 10
        ports:
          - 5432:5432

      redis:
        image: redis:4.0.14-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 2s
          --health-retries 10
        ports:
          - 6379:6379

    env:
      DATABASE_USERNAME: saturn
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      RAILS_ENV: test
      REDIS_URL: redis://redis:6379/0

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file .saturnci/Dockerfile --tag my-rails-app

    - name: Run tests
      run: docker run -e DATABASE_USERNAME -e DATABASE_HOST -e DATABASE_PORT -e RAILS_ENV -e REDIS_URL my-rails-app bundle exec rspec
